<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.19.2" />
    <PackageReference Include="AngleSharp" Version="1.8.1" />
    <PackageReference Include="NetVips" Version="3.2.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11"><PrivateAssets>all</PrivateAssets></PackageReference>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Loupe.Application/Loupe.Application.csproj" />
  </ItemGroup>
</Project>
